# config/routes.yaml

controllers:
  resource: "../src/Controller/"
  type: attribute

app_download_mail:
  path: "/download/mail/{filename}"
  controller: 'App\Controller\HomeController::downloadMail'
